name: "Hit a webhook"
 
on:
  push:
    tags:
      - '**'
 
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://novo.planetanaescola.com/wp-json/git-updater/v1/update/?key=2b0da6fd15f3c340c4ae8b8f5263f7a8&theme=planetanaescola"
